### ISSUE TITLE
problem starting plugin

### ISSUE THREAD

**Issue by fsosaaa** [Corenb/PremiumConnector#11]
this error appears when i try to start the plugin
info:
flamecord in his last version (V0.4.5)
plugins: authmebungee, PremiumConnector

**[01:35:57 WARN]: Error enabling plugin PremiumConnector
java.lang.NoClassDefFoundError: ml/karmaconfigs/lockloginmodules/shared/NoJarException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_271]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_271]
        at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:1.8.0_271]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:297) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
Caused by: java.lang.ClassNotFoundException: ml.karmaconfigs.lockloginmodules.shared.NoJarException
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[flamecord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a3b453d:unknown]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        ... 9 more**

**Comment by Corenb** [comment]
Duplicate #7
