### ISSUE TITLE
Error Waterfall

### ISSUE THREAD

**Issue by Euphillya** [Corenb/PremiumConnector#12]
`[09:30:56 WARN]: Error enabling plugin PremiumConnector
java.lang.NoClassDefFoundError: ml/karmaconfigs/lockloginmodules/shared/NoJarException
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_275]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_275]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_275]
        at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_275]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:382) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:243) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
Caused by: java.lang.ClassNotFoundException: ml.karmaconfigs.lockloginmodules.shared.NoJarException
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:fbaf9f6:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 9 more`

**Comment by Corenb** [comment]
Duplicate #7
