### ISSUE TITLE
Too long nick

### ISSUE THREAD

**Issue by SmigloNPC** [Corenb/PremiumConnector#13]
Hello
I notice that when player's nickname is 16 characters long console send error:
`[21:48:44 ERROR]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'Name' at row 1
[21:48:44 ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
[21:48:44 ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[21:48:44 ERROR]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[21:48:44 ERROR]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[21:48:44 ERROR]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[21:48:44 ERROR]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536)
[21:48:44 ERROR]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2585)
[21:48:44 ERROR]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1464)
[21:48:44 ERROR]: 	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[21:48:44 ERROR]: 	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[21:48:44 ERROR]: 	at eu.horyzon.premiumconnector.session.PlayerSession.update(PlayerSession.java:46)
[21:48:44 ERROR]: 	at eu.horyzon.premiumconnector.task.PremiumCheck.run(PremiumCheck.java:65)
[21:48:44 ERROR]: 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[21:48:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[21:48:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[21:48:44 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[21:48:44 WARN] [PremiumConnector]: SQL exception when trying to load TrevorPLLLLLLLLL account.`

Why is "Name" column limited to 15 characters?

**Comment by Corenb** [comment]
This varchar length is the default length used in (almost) all plugins cause Mojang limits Minecraft username to 15 chars.

You can modify yourself the database structure to allow more than 15 chars.
