### ISSUE TITLE
Error in BungeeCord Server

### ISSUE THREAD

**Issue by Tritton74** [Corenb/PremiumConnector#25]
Hello, i have this error : 

 Exception encountered when loading plugin: PremiumConnector
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
    at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
    at eu.horyzon.premiumconnector.sql.DataSource.<init>(DataSource.java:22)
    at eu.horyzon.premiumconnector.PremiumConnector.onEnable(PremiumConnector.java:76)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

I have this Plugins 👍 
![image](https://user-images.githubusercontent.com/79106616/107978175-a2c0a100-6fbc-11eb-9f75-605469e1c153.png)

How i can fix it ?

Thx :)

**Comment by Corenb** [comment]
What is your version of BungeeCord/Waterfall ? I guess if you update it to a newer version it works.
