### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by zuhir** [Corenb/PremiumConnector#6]
```
[PremiumConnector] LockLogin hook enabled.
19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)

19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)

19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)

19:37:50 [GRAVE]     at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.nio.file.Files.readAttributes(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.zip.ZipFile.<init>(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.zip.ZipFile.<init>(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.jar.JarFile.<init>(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.jar.JarFile.<init>(Unknown Source)

19:37:50 [GRAVE]     at java.base/java.util.jar.JarFile.<init>(Unknown Source)

19:37:50 [GRAVE]     at ml.karmaconfigs.lockloginmodules.bungee.ModuleLoader.inject(ModuleLoader.java:52)

19:37:50 [GRAVE]     at eu.horyzon.premiumconnector.PremiumConnector.onEnable(PremiumConnector.java:93)

19:37:50 [GRAVE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)

19:37:50 [GRAVE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)

19:37:50 [GRAVE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)

19:37:50 [GRAVE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
LockLogin loads correctly without errors

**Comment by Corenb** [comment]
Hello @zuhir , can u send me complete logs and your server version ? (Bungeecord ? Waterfall?)

**Comment by zuhir** [comment]
[log.log](https://github.com/Corenb/PremiumConnector/files/5675708/log.log)
Bungee log

Bungee version: git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539
Authlobby (and Lobby) has spigot 1.8.8-R0.1-SNAPSHOT (git-Spigot-21fe707-e1ebe52)

EDIT: my Windows is in Spanish, sorry for some texts in this lang

**Comment by Corenb** [comment]
It's an LockLogin issue, I discuss with LockLogin owner and he see 2 possible reasons : 
- Are you using Fat or Flat LockLogin version ?
- Try to rename your subfolder and remove escape (C:\Users\vento\Desktop\Network_1.8-1.16.4\Bungeecord_v1.0\)

**Comment by zuhir** [comment]
I changed "Network 1.8 - 1.16.4" to "Network" and now works correctly aparently. I just have this error now but i don't know if it is from premiumconnector, locklogin or another thing
```
[GRAVE] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

14:19:15 [GRAVE] SLF4J: Defaulting to no-operation (NOP) logger implementation

14:19:15 [GRAVE] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Log
[log.log](https://github.com/Corenb/PremiumConnector/files/5680621/log.log)

**Comment by Corenb** [comment]
Perfect ! This new error is from LockLogin plugin, maybe you can try to use the Fat version.

**Comment by zuhir** [comment]
> Perfect ! This new error is from LockLogin plugin, maybe you can try to use the Fat version.

SORRY!! When i tried to connect (i'm premium) i get this in bungee console:
```
14:30:27 [ADVERTENCIA] Error dispatching event ml.karmaconfigs.lockloginsystem.bungeecord.api.events.PlayerVerifyEvent@113a45cd to listener eu.horyzon.premiumconnector.listeners.LockLoginListener@49e4c2d5
java.lang.NullPointerException: info
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:252)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:209)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:191)
    at eu.horyzon.premiumconnector.PremiumConnector.redirect(PremiumConnector.java:155)
    at eu.horyzon.premiumconnector.listeners.LockLoginListener.onPlayerVerify(LockLoginListener.java:63)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
    at ml.karmaconfigs.lockloginsystem.bungeecord.commands.LoginCommand.execute(LoginCommand.java:61)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:154)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:71)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Unknown Source)
```

[log.log](https://github.com/Corenb/PremiumConnector/files/5680663/log.log)
