### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by KoxSosen** [Corenb/PremiumConnector#7]
[08:24:00] [main/WARN]: Error enabling plugin PremiumConnector
java.lang.NoClassDefFoundError: ml/karmaconfigs/lockloginmodules/shared/NoJarException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3342) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:415) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:316) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:339) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:83) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at eu.mikroskeem.firefly.Bootstrap.main(Bootstrap.java:130) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
Caused by: java.lang.ClassNotFoundException: ml.karmaconfigs.lockloginmodules.shared.NoJarException
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[fly.jar:git:Firefly-Proxy:1.16-SNAPSHOT:e35175a:unknown]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 13 more

**Comment by Corenb** [comment]
It gonna fixed in next release. Instead you can continue to use 2.2.1, nothing change between these 2 versions.
